spring.application.name=screenmatch
omdb.base-url=https://www.omdbapi.com/
omdb.api-key=${API_KEY}

google.translate.base-url=https://translation.googleapis.com/language/translate/v2
google.translate.api-key=${API_KEY_AI}