spring.application.name=screenmatch
spring.datasource.url=jdbc:postgresql://localhost/screenmatch
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect
spring.jpa.hibernate.ddl-auto=update
omdb.base-url=https://www.omdbapi.com/
omdb.api-key=${API_KEY}
google.translate.base-url=https://translation.googleapis.com/language/translate/v2
google.translate.api-key=${API_KEY_AI}
spring.jpa.show-sql=true
spring.jpa.format-sql=true